/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as StoreRouteImport } from './routes/store'
import { Route as RegistryIdRouteImport } from './routes/registry.$id'
import { Route as SpaceIndexRouteImport } from './routes/space/index'
import { Route as SpaceDaisyRouteImport } from './routes/space/daisy'
import { Route as SpaceExecutionRouteImport } from './routes/space/execution'
import { Route as SpaceNodesRouteImport } from './routes/space/nodes'
import { Route as SpaceProofsRouteImport } from './routes/space/proofs'
import { Route as StoreSkuRouteImport } from './routes/store.$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIdRoute = RegistryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RegistryRoute,
} as any)
const SpaceIndexRoute = SpaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpaceRoute,
} as any)
const SpaceDaisyRoute = SpaceDaisyRouteImport.update({
  id: '/daisy',
  path: '/daisy',
  getParentRoute: () => SpaceRoute,
} as any)
const SpaceExecutionRoute = SpaceExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => SpaceRoute,
} as any)
const SpaceNodesRoute = SpaceNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => SpaceRoute,
} as any)
const SpaceProofsRoute = SpaceProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => SpaceRoute,
} as any)
const StoreSkuRoute = StoreSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/cart': typeof CartRoute
  '/manifesto': typeof ManifestoRoute
  '/registry': typeof RegistryRouteWithChildren
  '/space': typeof SpaceRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/registry/$id': typeof RegistryIdRoute
  '/space/daisy': typeof SpaceDaisyRoute
  '/space/execution': typeof SpaceExecutionRoute
  '/space/nodes': typeof SpaceNodesRoute
  '/space/proofs': typeof SpaceProofsRoute
  '/store/$sku': typeof StoreSkuRoute
  '/space/': typeof SpaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/cart': typeof CartRoute
  '/manifesto': typeof ManifestoRoute
  '/registry': typeof RegistryRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/registry/$id': typeof RegistryIdRoute
  '/space/daisy': typeof SpaceDaisyRoute
  '/space/execution': typeof SpaceExecutionRoute
  '/space/nodes': typeof SpaceNodesRoute
  '/space/proofs': typeof SpaceProofsRoute
  '/store/$sku': typeof StoreSkuRoute
  '/space': typeof SpaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/demo': typeof DemoRoute
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/manifesto': typeof ManifestoRoute
  '/registry': typeof RegistryRouteWithChildren
  '/space': typeof SpaceRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/registry/$id': typeof RegistryIdRoute
  '/space/daisy': typeof SpaceDaisyRoute
  '/space/execution': typeof SpaceExecutionRoute
  '/space/nodes': typeof SpaceNodesRoute
  '/space/proofs': typeof SpaceProofsRoute
  '/store/$sku': typeof StoreSkuRoute
  '/space/': typeof SpaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/demo'
    | '/'
    | '/cart'
    | '/manifesto'
    | '/registry'
    | '/space'
    | '/store'
    | '/registry/$id'
    | '/space/daisy'
    | '/space/execution'
    | '/space/nodes'
    | '/space/proofs'
    | '/store/$sku'
    | '/space/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/demo'
    | '/'
    | '/cart'
    | '/manifesto'
    | '/registry'
    | '/store'
    | '/registry/$id'
    | '/space/daisy'
    | '/space/execution'
    | '/space/nodes'
    | '/space/proofs'
    | '/store/$sku'
    | '/space'
  id:
    | '__root__'
    | '/demo'
    | '/'
    | '/cart'
    | '/manifesto'
    | '/registry'
    | '/space'
    | '/store'
    | '/registry/$id'
    | '/space/daisy'
    | '/space/execution'
    | '/space/nodes'
    | '/space/proofs'
    | '/store/$sku'
    | '/space/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  CartRoute: typeof CartRoute
  ManifestoRoute: typeof ManifestoRoute
  RegistryRoute: typeof RegistryRouteWithChildren
  SpaceRoute: typeof SpaceRouteWithChildren
  StoreRoute: typeof StoreRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$id': {
      id: '/registry/$id'
      path: '/$id'
      fullPath: '/registry/$id'
      preLoaderRoute: typeof RegistryIdRouteImport
      parentRoute: typeof RegistryRoute
    }
    '/space/': {
      id: '/space/'
      path: '/'
      fullPath: '/space/'
      preLoaderRoute: typeof SpaceIndexRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/space/daisy': {
      id: '/space/daisy'
      path: '/daisy'
      fullPath: '/space/daisy'
      preLoaderRoute: typeof SpaceDaisyRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/space/execution': {
      id: '/space/execution'
      path: '/execution'
      fullPath: '/space/execution'
      preLoaderRoute: typeof SpaceExecutionRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/space/nodes': {
      id: '/space/nodes'
      path: '/nodes'
      fullPath: '/space/nodes'
      preLoaderRoute: typeof SpaceNodesRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/space/proofs': {
      id: '/space/proofs'
      path: '/proofs'
      fullPath: '/space/proofs'
      preLoaderRoute: typeof SpaceProofsRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/store/$sku': {
      id: '/store/$sku'
      path: '/$sku'
      fullPath: '/store/$sku'
      preLoaderRoute: typeof StoreSkuRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface RegistryRouteChildren {
  RegistryIdRoute: typeof RegistryIdRoute
}

const RegistryRouteChildren: RegistryRouteChildren = {
  RegistryIdRoute: RegistryIdRoute,
}

const RegistryRouteWithChildren = RegistryRoute._addFileChildren(
  RegistryRouteChildren,
)

interface SpaceRouteChildren {
  SpaceDaisyRoute: typeof SpaceDaisyRoute
  SpaceExecutionRoute: typeof SpaceExecutionRoute
  SpaceNodesRoute: typeof SpaceNodesRoute
  SpaceProofsRoute: typeof SpaceProofsRoute
  SpaceIndexRoute: typeof SpaceIndexRoute
}

const SpaceRouteChildren: SpaceRouteChildren = {
  SpaceDaisyRoute: SpaceDaisyRoute,
  SpaceExecutionRoute: SpaceExecutionRoute,
  SpaceNodesRoute: SpaceNodesRoute,
  SpaceProofsRoute: SpaceProofsRoute,
  SpaceIndexRoute: SpaceIndexRoute,
}

const SpaceRouteWithChildren = SpaceRoute._addFileChildren(SpaceRouteChildren)

interface StoreRouteChildren {
  StoreSkuRoute: typeof StoreSkuRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreSkuRoute: StoreSkuRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  CartRoute: CartRoute,
  ManifestoRoute: ManifestoRoute,
  RegistryRoute: RegistryRouteWithChildren,
  SpaceRoute: SpaceRouteWithChildren,
  StoreRoute: StoreRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
