import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import ordersRouter from "./orders";
import vaultRouter from "./vault";
import libraryRouter from "./library";
import problemsRouter from "./problems";
import solutionsRouter from "./solutions";
import escrowRouter from "./escrow";
import crawlerRouter from "./crawler";
import notificationsRouter from "./notifications";
import earningsRouter from "./earnings";
import offersRouter from "./offers";
import ownerRouter from "./owner";
import brainRouter from "./brain";
import telemetryRouter from "./telemetry";
import signerRouter from "./signer";
import stripeRouter from "./stripe";
import cryptoRouter from "./crypto";
import kineticRouter from "./kinetic";
import deliveryRouter from "./delivery";
import challengesRouter from "./challenges";
import quantumRouter from "./quantum";
import openaiRouter from "./openai";
import outreachRouter from "./outreach";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(vaultRouter);
router.use(libraryRouter);
router.use(problemsRouter);
router.use(solutionsRouter);
router.use(escrowRouter);
router.use(crawlerRouter);
router.use(notificationsRouter);
router.use(earningsRouter);
router.use(offersRouter);
router.use(ownerRouter);
router.use(brainRouter);
router.use(telemetryRouter);
router.use(signerRouter);
router.use(stripeRouter);
router.use(cryptoRouter);
router.use(kineticRouter);
router.use(deliveryRouter);
router.use(challengesRouter);
router.use(quantumRouter);
router.use(openaiRouter);
router.use(outreachRouter);

export default router;
