import React, { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, ExternalLink, Lock, RefreshCw, ShieldCheck } from 'lucide-react';

interface PayPalHubProps { onStatusChanged: (configured: boolean) => void; }
interface GatewayInfo { configured: boolean; environment: 'sandbox' | 'live' | 'none'; gateway_state: string; webhook_configured: boolean; }

/** Credentials are deployment secrets, never a browser form field. */
export const PayPalHub: React.FC<PayPalHubProps> = ({ onStatusChanged }) => {
  const [info, setInfo] = useState<GatewayInfo | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); setError(null); try { const response = await fetch('/api/payments/paypal/status'); if (!response.ok) throw new Error('Unable to retrieve payment gateway status'); const data = await response.json(); setInfo(data); onStatusChanged(Boolean(data.configured)); } catch (reason: any) { setError(reason.message || 'Unable to retrieve gateway status'); onStatusChanged(false); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  return <div className="space-y-6"><section className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6"><div className="flex flex-col sm:flex-row justify-between gap-4"><div><h2 className="text-xl font-bold text-white">PayPal Commercial Gateway</h2><p className="mt-2 text-sm text-slate-400">The browser never receives PayPal client secrets. Credentials and webhook identity are deployment-only server configuration.</p></div><button onClick={refresh} className="px-3 py-2 rounded-lg bg-slate-800 text-slate-200 text-xs flex items-center gap-2"><RefreshCw className="w-3 h-3"/>Refresh status</button></div></section>
  {loading ? <p className="text-sm text-slate-400">Checking server configuration…</p> : error ? <p className="p-4 rounded-xl border border-rose-800 bg-rose-950/30 text-rose-200 text-sm">{error}</p> : <><section className={`p-5 rounded-2xl border ${info?.configured ? 'border-emerald-800 bg-emerald-950/20' : 'border-amber-800 bg-amber-950/20'}`}><div className="flex items-center gap-3">{info?.configured ? <CheckCircle2 className="w-5 h-5 text-emerald-400"/> : <AlertTriangle className="w-5 h-5 text-amber-400"/>}<div><h3 className="text-white font-semibold">{info?.configured ? `Server credentials configured (${info.environment})` : 'Credentials not configured'}</h3><p className="text-xs text-slate-400 mt-1">Gateway state: {info?.gateway_state}</p></div></div></section>
  <section className="grid md:grid-cols-3 gap-4 text-sm"><div className="p-4 rounded-xl bg-slate-900 border border-slate-800"><Lock className="w-4 h-4 text-cyan-400 mb-2"/><strong className="text-white block">Server-only secrets</strong><span className="text-slate-400 text-xs">Set PayPal values in the deployment secret store. No client form or session credential path exists.</span></div><div className="p-4 rounded-xl bg-slate-900 border border-slate-800"><ShieldCheck className="w-4 h-4 text-cyan-400 mb-2"/><strong className="text-white block">USD settlement</strong><span className="text-slate-400 text-xs">Checkout uses the stored order amount in USD. No extra asset policy is required.</span></div><div className="p-4 rounded-xl bg-slate-900 border border-slate-800"><AlertTriangle className="w-4 h-4 text-cyan-400 mb-2"/><strong className="text-white block">Webhook verification</strong><span className="text-slate-400 text-xs">Webhook ID configured: {String(info?.webhook_configured)}. Live payments fail closed without it.</span></div></section>
  <section className="p-5 rounded-2xl bg-slate-900/70 border border-slate-800 text-sm"><h3 className="text-white font-semibold">Deployment checklist</h3><ol className="mt-3 list-decimal list-inside text-slate-400 space-y-1"><li>Configure server-only sandbox or live PayPal credentials.</li><li>Register the PayPal webhook and set <code>PAYPAL_WEBHOOK_ID</code>.</li><li>Use server-issued authentication tokens to create orders and checkout sessions.</li></ol><a className="inline-flex items-center gap-1 mt-4 text-xs text-blue-300" href="https://developer.paypal.com/docs/api/overview/" target="_blank" rel="noreferrer">PayPal REST API <ExternalLink className="w-3 h-3"/></a></section></>}
  </div>;
};
