// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wall-street/Storefront.tsx": () => import("../components/mockups/wall-street/Storefront.tsx"),
  "./components/mockups/wall-street/ValidationSandbox.tsx": () => import("../components/mockups/wall-street/ValidationSandbox.tsx")
};
