import fs from 'node:fs';
import path from 'node:path';

const candidateId = 'DH-C-B28A191DCBFE70D0';
const env = process.env.SOLVEX_ENVIRONMENT || process.env.SOLVEX_ENV || 'UNKNOWN';
const read = (name: string) => { try { return JSON.parse(fs.readFileSync(path.join('artifacts', name), 'utf8')); } catch { return undefined; } };
const production = read('SOLVEX-PRODUCTION-READINESS-REPORT.json');
const database = read('SOLVEX-DATABASE-READINESS.json');
const b2b = read('SOLVEX-B2B-ACCEPTANCE-READINESS.json');
const paypal = read('SOLVEX-PAYPAL-READINESS.json');
const webhooks = read('SOLVEX-WEBHOOK-VERIFICATION.json');
const marketplace = read('SOLVEX-MARKETPLACE-GATE-REPORT.json');
const security = read('SOLVEX-SECURITY-VERIFICATION.json');
const recovery = read('SOLVEX-RECOVERY-READINESS.json');
const technical = read(`candidate-verification-${candidateId}.json`);
const inventory = read('SOLVEX-PRODUCTION-READINESS-INVENTORY.json');
const connected = read('CONNECTED-SERVICE-READINESS.json');
const neonSchema = read('NEON-PRODUCTION-SCHEMA-VERIFICATION.json');
const neonConnected = Boolean(connected?.services?.neon?.enabled && neonSchema?.branch_state === 'ready');
const paypalConnected = Boolean(connected?.services?.paypal?.enabled);
const statuses = {
  TECHNICAL_VERIFICATION: { status: 'VERIFIED_IMPLEMENTATION', evidence: technical ? 'Candidate-specific SMT proof, Z3 WASM UNSAT, hermetic execution, independent oracle, and cleanroom replay artifact present.' : 'Candidate artifact missing.', test: 'npm run verify:candidate', remaining_requirement: 'None for the local implementation contract; external B2B evidence is separate.' },
  B2B_REFERENCE_FRAMEWORK: { status: 'VERIFIED_IMPLEMENTATION', evidence: b2b?.evidence || 'Server-authoritative reference/evaluation workflow implemented.', test: 'npm run verify:b2b', remaining_requirement: 'Use a legitimate authorized business case; synthetic data remains excluded.' },
  CUSTOMER_ACCEPTANCE: { status: 'BLOCKED', evidence: 'MISSING — no customer or authorized evaluator supplied.', test: 'npm run verify:b2b; synthetic acceptance negative gate passed.', remaining_requirement: 'Actual authorized evaluator/customer, case definition, execution, review, and acceptance decision.' },
  INDEPENDENT_B2B_EVIDENCE: { status: 'BLOCKED', evidence: 'MISSING — no independent external evidence supplied.', test: 'npm run verify:commercial; independent-evidence gate remains blocked.', remaining_requirement: 'Separate independent evaluator, methodology, observed result, authorization, and hash-linked evidence.' },
  AUTHENTICATION: { status: 'PARTIAL', evidence: 'Local HMAC server verification and tenant/RBAC tests pass; production IDP is not configured.', test: 'npm run verify:enterprise and npm run verify:security', remaining_requirement: 'Production IDP issuer/client/secret and deployed role/resource ownership verification.' },
  DATABASE: { status: neonConnected ? 'PARTIAL' : (database?.status || 'BLOCKED'), evidence: neonConnected ? `Neon SolveX production branch is ready with ${neonSchema.tables_verified} tables and ${neonSchema.indexes_verified} indexes; RLS policy count is ${neonSchema.rls_policy_count}. Application runtime binding and restart readback remain unverified.` : (database?.evidence || 'Local SQLite only; managed production database not verified.'), test: neonConnected ? 'Neon read-only project, branch, schema, index, and RLS inspection' : 'npm run verify:production', remaining_requirement: neonConnected ? 'Bind the deployed app to the Neon branch, apply reviewed RLS policies, verify migrations/transactions, and prove restart readback.' : (database?.remaining_requirement || 'Managed database, migrations, indexes, RLS, transactions, and restart readback.') },
  TENANT_ISOLATION: { status: 'VERIFIED_IMPLEMENTATION', evidence: 'Local repository tenant scoping and cross-tenant denial tests pass.', test: 'npm run verify:enterprise and npm run verify:security', remaining_requirement: 'Managed production RLS deployment and independent verification.' },
  PAYPAL_SANDBOX: { status: paypalConnected ? 'PARTIAL' : (paypal?.status === 'NOT_CONFIGURED' ? 'NOT_CONFIGURED' : 'PARTIAL'), evidence: paypalConnected ? 'PayPal for Business connector is active; read-only transaction query returned no transactions. No payment was created or captured.' : (paypal?.evidence || 'No sandbox provider credentials detected; no transaction executed.'), test: paypalConnected ? 'PayPal read-only transaction query; no payment mutation attempted' : 'npm run verify:payment', remaining_requirement: 'Bind application runtime credentials, verify environment/webhook identity, and complete a non-destructive provider-authenticated readiness path.' },
  PAYPAL_PRODUCTION: { status: paypalConnected ? 'PARTIAL' : 'NOT_CONFIGURED', evidence: paypalConnected ? 'PayPal for Business connector is active, but application runtime credentials and provider-authenticated capture evidence are not verified. No transactions were found in the inspected window.' : 'No live credentials or production provider operation detected.', test: paypalConnected ? 'PayPal read-only transaction query; no payment mutation attempted' : 'npm run verify:payment and npm run verify:secrets', remaining_requirement: 'Bind the application to the intended PayPal environment, verify webhook configuration, and obtain a provider-authenticated PayPal transaction with matching order evidence.' },
  PAYPAL_WEBHOOKS: { status: webhooks?.status || 'BLOCKED', evidence: webhooks?.evidence || 'Unconfigured webhook event rejected fail-closed.', test: 'npm run verify:webhooks', remaining_requirement: 'Provider-signed webhook verification, event persistence, idempotency, replay rejection, and tenant/order binding.' },
  PAYPAL: { status: 'NOT_OBSERVED', evidence: 'No provider-authenticated PayPal transaction evidence observed.', test: 'npm run verify:payment; capture path verifies the PayPal order, capture, amount, currency, webhook, and tenant binding.', remaining_requirement: 'Provider-authenticated PayPal transaction evidence with matching stored order and webhook audit trail.' },
  MARKETPLACE: { status: marketplace?.status || 'BLOCKED', evidence: marketplace?.evidence || 'No offer published; missing B2B and independent evidence.', test: 'npm run verify:marketplace', remaining_requirement: marketplace?.remaining_requirement || 'All technical, B2B, independent, authorization, tenant, production, and evidence gates.' },
  ORDERS: { status: 'VERIFIED_IMPLEMENTATION', evidence: 'Server-side order state and payment binding code exists; no commercial order executed.', test: 'npm run verify:api and npm run verify:enterprise', remaining_requirement: 'Published verified offer, real customer order, provider-confirmed payment, and audited transitions.' },
  FULFILLMENT: { status: 'BLOCKED', evidence: 'No fulfillment executed.', test: 'Negative order/payment gates and lifecycle inspection', remaining_requirement: 'Real verified offer, payment confirmation, explicit fulfillment authorization, delivery evidence, and rollback plan.' },
  PRODUCTION_DEPLOYMENT: { status: 'BLOCKED', evidence: production?.evidence || 'Production environment and managed secrets/database are not configured.', test: 'npm run verify:production', remaining_requirement: 'Managed deployment with production IDP, database, secret management, monitoring, backups, and provider configuration.' },
  MONITORING: { status: 'PARTIAL', evidence: 'Local audit/telemetry interfaces exist; no production monitoring deployment evidence.', test: 'npm run verify:nodes and source inventory', remaining_requirement: 'Production metrics, logs, alerts, security events, retries, replays, and rollback monitoring.' },
  BACKUPS: { status: 'BLOCKED', evidence: 'No managed backup/restore evidence performed.', test: 'npm run verify:recovery', remaining_requirement: 'Restorable managed database backup and audit-preservation rehearsal.' },
  RECOVERY: { status: recovery?.status || 'PARTIAL', evidence: recovery?.evidence || 'Local checkpoint/diversion path tested only.', test: 'npm run verify:recovery', remaining_requirement: recovery?.remaining_requirement || 'Production recovery rehearsal.' },
  SECURITY: { status: 'PARTIAL', evidence: security?.evidence || 'Local negative security tests pass.', test: 'npm run verify:security', remaining_requirement: security?.remaining_requirement || 'Independent production security review.' },
  OVERALL_COMMERCIAL_STATE: { status: 'BLOCKED', evidence: 'Technical implementation is proven locally, but B2B acceptance, independent evidence, payment, production configuration, and marketplace gates are missing.', test: 'npm run verify:all', remaining_requirement: 'Stop at the first missing external prerequisite; do not manufacture customer or payment evidence.' }
};
const report = { timestamp: new Date().toISOString(), environment: env.toUpperCase(), source_revision: 'SOURCE_SNAPSHOT_UNVERSIONED', candidate_id: candidateId, implementation_hash: 'b28a191dcbfe70d02e98455d09982b93db4b2561243e558ee9f73ba2c74cdcd5', inventory_reference: 'SOLVEX-PRODUCTION-READINESS-INVENTORY.json', connected_services: connected?.services || {}, neon_schema_reference: 'NEON-PRODUCTION-SCHEMA-VERIFICATION.json', statuses };
fs.mkdirSync('artifacts', { recursive: true });
fs.writeFileSync('artifacts/SOLVEX-PRODUCTION-READINESS-REPORT.json', JSON.stringify(report, null, 2));
const md = ['# SOLVEX Production Readiness Report', '', `- **Environment:** ${report.environment}`, `- **Candidate:** ${candidateId}`, `- **Implementation hash:** ${report.implementation_hash}`, '', '## Connected services', '', neonConnected ? `Neon SolveX production branch is **ready** with ${neonSchema.tables_verified} tables and ${neonSchema.indexes_verified} indexes; **RLS policies detected: ${neonSchema.rls_policy_count}**.` : 'Neon production branch not verified.', paypalConnected ? 'PayPal for Business connector is **active**; read-only transaction inspection found no transactions. No payment was created, captured, or moved.' : 'PayPal connector not verified.', '', '## Truth classification', '', '| Area | Status | Evidence | Test | Remaining requirement |', '|---|---|---|---|---|'];
for (const [area, value] of Object.entries(statuses)) {
  const evidence = typeof value.evidence === 'string' ? value.evidence : JSON.stringify(value.evidence);
  md.push(`| ${area} | **${value.status}** | ${evidence.replace(/\n/g, ' ')} | ${value.test} | ${value.remaining_requirement} |`);
}
md.push('', '## Explicit boundary', '', 'Connector availability is not equivalent to application runtime configuration, provider-authenticated PayPal payment evidence, customer acceptance, or production commercial readiness.', 'No customer, evaluator, acceptance, revenue, payment, production deployment, or external verification was invented.');
fs.writeFileSync('artifacts/SOLVEX-PRODUCTION-READINESS-REPORT.md', md.join('\n') + '\n');
console.log(JSON.stringify({ artifact_json: 'artifacts/SOLVEX-PRODUCTION-READINESS-REPORT.json', artifact_markdown: 'artifacts/SOLVEX-PRODUCTION-READINESS-REPORT.md', overall: statuses.OVERALL_COMMERCIAL_STATE.status }, null, 2));
