import React, { useEffect, useState } from 'react';
import { ShoppingCart, Activity, Key } from 'lucide-react';
import { Header } from './components/Header';
import { PayPalHub } from './components/PayPalHub';
import { MarketplaceView } from './components/MarketplaceView';
import { ClientRole, ClientUserContext } from './clientTypes';

type ActiveTab = 'OVERVIEW' | 'PAYPAL' | 'MARKETPLACE';
const tabs: Array<{ id: ActiveTab; label: string; Icon: any }> = [
  { id: 'OVERVIEW', label: 'Overview', Icon: Activity }, { id: 'PAYPAL', label: 'PayPal', Icon: Key }, { id: 'MARKETPLACE', label: 'Marketplace', Icon: ShoppingCart }
];

export default function App() {
  const [activeTab, setActiveTab] = useState<ActiveTab>('OVERVIEW');
  const [activeTenant, setActiveTenant] = useState('TENANT_ENTERPRISE_DEMO');
  const [currentUser, setCurrentUser] = useState<ClientUserContext>({ user_id: 'browser-display-only', tenant_id: 'TENANT_ENTERPRISE_DEMO', email: 'unauthenticated@browser.local', role: 'CUSTOMER' });
  const [chainValid, setChainValid] = useState(false); const [paypalConnected, setPaypalConnected] = useState(false);
  const refreshSystemStatus = async () => { try { const response = await fetch('/api/system/health'); const health = await response.json(); setChainValid(Boolean(health.audit_chain_continuous)); } catch { setChainValid(false); } };
  useEffect(() => { void refreshSystemStatus(); }, []);
  return <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans"><Header currentUser={currentUser} onRoleChange={(role: ClientRole) => setCurrentUser(user => ({ ...user, role }))} activeTenant={activeTenant} onTenantChange={tenant => { setActiveTenant(tenant); setCurrentUser(user => ({ ...user, tenant_id: tenant })); }} chainValid={chainValid} auditHead="" paypalConnected={paypalConnected} onOpenPayPalHub={() => setActiveTab('PAYPAL')} /><nav className="border-b border-slate-800 bg-slate-900/50 px-4"><div className="max-w-7xl mx-auto flex gap-1 py-2 overflow-x-auto">{tabs.map(({ id, label, Icon }) => <button key={id} onClick={() => setActiveTab(id)} className={`px-3 py-1.5 rounded-lg text-xs flex items-center gap-2 ${activeTab === id ? 'bg-slate-700 text-white' : 'text-slate-400 hover:bg-slate-900'}`}><Icon className="w-3.5 h-3.5"/>{label}</button>)}</div></nav><main className="flex-1 max-w-7xl w-full mx-auto p-4 lg:p-8">{activeTab === 'OVERVIEW' && <section className="space-y-5"><div className="bg-slate-900 border border-slate-800 rounded-3xl p-8"><span className="text-xs text-cyan-300 font-mono">PRODUCTION-ORIENTED / FAIL-CLOSED</span><h1 className="mt-3 text-3xl font-bold">SOLVEX B2B evidence-gated commerce</h1><p className="mt-3 max-w-3xl text-slate-400">Daisy candidate generation, solution verification, marketplace publication, payment verification, and fulfillment each have separate evidence boundaries. Browser display settings do not confer authorization.</p></div><div className="grid md:grid-cols-3 gap-4"><div className="p-5 bg-slate-900 border border-slate-800 rounded-2xl"><b className="text-white">Daisy</b><p className="mt-2 text-sm text-slate-400">Static candidate intake is executable; candidates remain PARTIAL without sandboxed test evidence and independent verification.</p></div><div className="p-5 bg-slate-900 border border-slate-800 rounded-2xl"><b className="text-white">Marketplace</b><p className="mt-2 text-sm text-slate-400">Only exact solution/proof/implementation hash bindings may publish. There are no seeded commercial listings.</p></div><div className="p-5 bg-slate-900 border border-slate-800 rounded-2xl"><b className="text-white">Payments</b><p className="mt-2 text-sm text-slate-400">PayPal OAuth, Orders v2, capture re-read, webhook signature verification, and provider capture evidence are server-side gates.</p></div></div></section>}{activeTab === 'PAYPAL' && <PayPalHub onStatusChanged={setPaypalConnected} />}{activeTab === 'MARKETPLACE' && <MarketplaceView onNavigateToPayPal={() => setActiveTab('PAYPAL')} onNavigateToEvidence={() => undefined} />}</main><footer className="border-t border-slate-800 py-4 px-6 text-xs text-slate-500 font-mono">SOLVEX • evidence gates active • browser display is non-authoritative</footer></div>;
}
